<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-07-21T07:23:50+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Amsterdam',
];
