<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-07-26T11:31:47+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.2.1',
    'version_db_installed' => '20170802000000',
    'misc' => [
        'do_page_reindex_check' => false,
    ],
];
