<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-07-16T16:53:16+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'veganific',
        ],
    ],
];
