<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-12-01T23:23:24+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Flexim',
        ],
    ],
];
