<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-07-21T22:20:44+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'flexim',
        ],
    ],
];
