<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-06-08T09:00:41+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Berlin',
];
