<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-07-23T09:40:58+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Amsterdam',
];
