<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-07-23T10:12:44+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.clear.thumbnails
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.2.1',
    'version_db_installed' => '20170802000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1532331765,
    ],
    'cache' => [
        'clear' => [
            'thumbnails' => true,
        ],
    ],
];
