<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-07-23T10:12:35+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.editor.ckeditor4.plugins.selected
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Flexim',
            'editor' => [
                'concrete' => [
                    'enable_filemanager' => '1',
                    'enable_sitemap' => '1',
                ],
                'ckeditor4' => [
                    'plugins' => [
                        'selected' => [
                            'concrete5filemanager',
                            'concrete5inline',
                            'concrete5uploadimage',
                            'dialogadvtab',
                            'divarea',
                            'floatingspace',
                            'normalizeonchange',
                            'resize',
                            'toolbar',
                            'wysiwygarea',
                            'about',
                            'autogrow',
                            'a11yhelp',
                            'basicstyles',
                            'clipboard',
                            'colorbutton',
                            'colordialog',
                            'contextmenu',
                            'div',
                            'elementspath',
                            'enterkey',
                            'entities',
                            'format',
                            'htmlwriter',
                            'image',
                            'image2',
                            'indentblock',
                            'indentlist',
                            'justify',
                            'list',
                            'liststyle',
                            'magicline',
                            'removeformat',
                            'showblocks',
                            'showborders',
                            'sourcearea',
                            'sourcedialog',
                            'stylescombo',
                            'tab',
                            'table',
                            'tableresize',
                            'tableselection',
                            'tabletools',
                            'undo',
                            'concrete5link',
                            'concrete5styles',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
